### ISSUE TITLE
tasks/New-Release.GitHub.build.ps1 displays token

### ISSUE THREAD

**Issue by phbits** [gaelcolas/Sampler.GitHubTasks#17]
When publishing a release, the token is printed back to the screen at:

https://github.com/gaelcolas/Sampler.GitHubTasks/blob/main/.build/tasks/New-Release.GitHub.build.ps1#L112

```powershell
$getGHReleaseParams = @{
    Tag            = $ReleaseTag
    AccessToken    = $GitHubToken
    OwnerName      = $repoInfo.Owner
    RepositoryName = $repoInfo.Repository
    ErrorAction    = 'Stop'
}

Write-Build DarkGray "Checking if the Release exists: `r`n Get-GithubRelease $($getGHReleaseParams | Out-String)"
```

## Option 1 ##
I worked with @johlju on [Hide-GitToken](https://github.com/dsccommunity/DscResource.DocGenerator/blob/main/source/Private/Hide-GitToken.ps1) for DscResource.DocGenerator. That could be brought over and used for this.

## Option 2 ##
Don't display the token at all.

```powershell
$displayGHReleaseParams = $getGHReleaseParams.Clone()
$displayGHReleaseParams.Remove('AccessToken')
Write-Build DarkGray "Checking if the Release exists: `r`n Get-GithubRelease $($displayGHReleaseParams | Out-String)"
```

**Comment by johlju** [comment]
Suggest removing the token entirely.
